channels:
  - defaults
dependencies:
  - pip
  - pip:
    - attrdict
    - cdsapi
    - configobj
    - numpy
    - pandas
    - regex
    - scikit-image
    - torch
    - torchvision
    - tqdm
    - wandb
    - wget
    - xarray
    - einops
